import { useState } from "react";

/**
 * Renders a generated cover image for a blog post if one exists at
 * /images/blog/<slug>.png — silently hides if not found.
 *
 * Generated by `node scripts/generate-blog-covers.mjs` (uses Nano Banana
 * or Imagen 4). See scripts/cover-prompts.mjs for per-post prompts.
 */
interface Props {
  slug: string;
  alt: string;
  className?: string;
  loading?: "eager" | "lazy";
}

const BlogCover = ({ slug, alt, className, loading = "lazy" }: Props) => {
  const [missing, setMissing] = useState(false);
  if (missing) return null;
  return (
    <img
      src={`/images/blog/${slug}.png`}
      alt={alt}
      loading={loading}
      onError={() => setMissing(true)}
      className={className}
      draggable={false}
    />
  );
};

export default BlogCover;
